default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: NoiseCloud_development

test:
  <<: *default
  database: NoiseCloud_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: verify-full
  sslrootcert: <%= Rails.root.join("config/ssl/root.crt") %>